services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3030:3000

  api:
    image: directus/directus:10
    restart: always
    ports:
      - 8055:8055
    depends_on:
      - db
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_VERSION: "14"
      WEBSOCKETS_ENABLED: false
      TELEMETRY: false
      GRAPHQL_INTROSPECTION: false
      CACHE_ENABLED: false
      WEBSOCKETS_GRAPHQL_ENABLED: false
      CORS_CREDENTIALS: true
      CORS_ENABLED: true

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    #ports:
      #- 5432:5432
      
volumes:
  postgres: {}
