const data = [
  {
    entidad: "12",
    resultSujetosObligados: 285,
    resultOIC: 222,
    resultSistema1: 3,
    resultSistema2: 3,
    resultSistema3OIC: 5,
    resultSistema6: 2,
    resultConexiones: 1,
    resultTribunal: 0,
    resultSistema3Tribunal: 0,
  },
  {
    entidad: "30",
    resultSujetosObligados: 471,
    resultOIC: 424,
    resultSistema1: 5,
    resultSistema2: 2,
    resultSistema6: 3,
    resultTribunal: 0,
    resultSistema3OIC: 0,
    resultSistema3Tribunal: 0,
    resultConexiones: 0,
  },
  {
    entidad: "01",
    resultSujetosObligados: 96,
    resultOIC: 72,
    resultSistema1: 94,
    resultSistema2: 91,
    resultSistema3OIC: 71,
    resultSistema6: 2,
    resultConexiones: 1,
    resultTribunal: 0,
    resultSistema3Tribunal: 0,
  },
];

export default data;
