const data = [
  { id: "01", nombre: "Aguascalientes" },
  { id: "02", nombre: "Baja California" },
  { id: "03", nombre: "Baja California Sur" },
  { id: "04", nombre: "Campeche" },
  { id: "05", nombre: "Coahuila de Zaragoza" },
  { id: "06", nombre: "Colima" },
  { id: "07", nombre: "Chiapas" },
  { id: "08", nombre: "Chihuahua" },
  { id: "09", nombre: "Ciudad de México" },
  { id: "10", nombre: "Durango" },
  { id: "11", nombre: "Guanajuato" },
  { id: "12", nombre: "Guerrero" },
  { id: "13", nombre: "Hidalgo" },
  { id: "14", nombre: "Jalisco" },
  { id: "15", nombre: "México" },
  { id: "16", nombre: "Michoacán de Ocampo" },
  { id: "17", nombre: "Morelos" },
  { id: "18", nombre: "Nayarit" },
  { id: "19", nombre: "Nuevo León" },
  { id: "20", nombre: "Oaxaca" },
  { id: "21", nombre: "Puebla" },
  { id: "22", nombre: "Querétaro" },
  { id: "23", nombre: "Quintana Roo" },
  { id: "24", nombre: "San Luis Potosí" },
  { id: "25", nombre: "Sinaloa" },
  { id: "26", nombre: "Sonora" },
  { id: "27", nombre: "Tabasco" },
  { id: "28", nombre: "Tamaulipas" },
  { id: "29", nombre: "Tlaxcala" },
  { id: "30", nombre: "Veracruz de Ignacio de la Llave" },
  { id: "31", nombre: "Yucatán" },
  { id: "32", nombre: "Zacatecas" },
];

export default data;
